### ISSUE TITLE
Question: Should hot reload work or is watch only continous building without hot reload in browser?

### ISSUE THREAD

**Issue by oweitman** [AlCalzone/create-adapter#1003]
at the moment it didnt work, but i dont know if it should.
if not i have to reload with f5 in the browser?

**Comment by AlCalzone** [comment]
Did you mean to open this issue in the dev-server repo?

Also please at least give some details: commands you used, logs, etc.

**Comment by oweitman** [comment]
No, i tried this with the devcontainer and there ist no extra repo for the devcontainer.

**Comment by AlCalzone** [comment]
Ok, I'll need @UncleSamSwiss to answer this then.

**Comment by mcm1957** [comment]
As @AlCalzone already mentioned, I too do not think that this is the right place to discuss. The adapter creator provides a basic infrastructire. As far as I see this question releated to the dev-server environment and should be discussed there (if it is a issue) or better at telegram / discord channels:

iobroker adapter development starters: https://t.me/+gsX-e8k4mLtmZjZk
iobroker adapter entwicklung:                https://t.me/ioBroker_developmnt

I cannot answer whether pressing F5 to reload should be required or not when developing gui part. I suggest to press F5 at least as a workaround if this is working for you.

@AlCalzone 
@UncleSamSwiss 
@Apollon77

**Comment by AlCalzone** [comment]
This issue is not actionable without any details how we can reproduce without spending an hour to try and figure out what you did.

Feel free to open a new one with more details. German is fine if that's easier for you @oweitman.

**Comment by oweitman** [comment]
it is not an issue, it is a question if hot reloading should work
at the moment of this question, the hot reload is not working.
i have the feeling that you didnt read it in detail (and it is only one sentence)

**Comment by AlCalzone** [comment]
I don't know how/what to answer since your question doesn't provide enough context **what specifically** you're asking about.

If you can provide a **concrete** example where hot reload is not working, someone may be able to give you a proper answer.
