### ISSUE TITLE
Node updates - remove node 14, add node 20

### ISSUE THREAD

**Issue by mcm1957** [AlCalzone/create-adapter#1032]
I would suggest to remove support for node 14 and to add support for node 20:

-) at selection of minimum node required (maybe do not yet support node 20 only)
-) at generated test environment

**Comment by AlCalzone** [comment]
Wanna give a PR a shot? 😇

**Comment by mcm1957** [comment]
Ok.ill try to find the correct code parts.

**Comment by AlCalzone** [comment]
Happy to answer questions

**Comment by mcm1957** [comment]
OK, I should be able to change testing setup as this seems to be stored at template tree. I'll change as soon as I have a little bit ore time (PR requires test setup etc.)

I doubt that I can change the question to select node 14 / 16 as minimum. Tool is written in truescript and I do not understand truescript neither do I have any idea how to build / test truescript.

**Comment by AlCalzone** [comment]
> neither do I have any idea how to build / test true script

Just follow the checklist in the PR. Part of that builds the code. If anything breaks it will show you where.

You should be able to find the locations that are relevant by searching for 14 or 16 or 18 inside ts files.

**Comment by mcm1957** [comment]
Node releases specified at test-and-release.yml workflow changed and provided by PR https://github.com/ioBroker/create-adapter/pull/1040.

Adaption of paramater question still open - I did not yet find the file containing the question ...

**Comment by AlCalzone** [comment]
Thanks. Will review this and the other PRs tomorrow

**Comment by mcm1957** [comment]
second part fixed (or at least tried to fix :-) with PR #1042.

So IF both PRs can be accepted this issue can be closed. I did not use "closes" remark as I do not know how toi specify the fact that two PRs are required for this issue to close completly (if it even possible). And I preferred to split the PRs as changing th workflow yml seems to be a lot easier / error proff as changing the questions sequence. Hopw that OK this way.

Fell free to give some feedback if I can fix anything

**Comment by mcm1957** [comment]
@AlCalzone 
> Thanks. Will review this and the other PRs tomorrow

Don't want to put stress onto you. This is only a kindly reminder of the openPRs - may be those are forgotten due to importent work etc.

If you do not have time - no hurry !

If I should fix / change something, please let me know.

https://github.com/ioBroker/create-adapter/pull/1039
https://github.com/ioBroker/create-adapter/pull/1040
https://github.com/ioBroker/create-adapter/pull/1041
