### ISSUE TITLE
Bump ecmaVersion to 2022 at .eslintcr.json

### ISSUE THREAD

**Issue by mcm1957** [AlCalzone/create-adapter#1047]
I would suggest to change .eslintrc.json to define ecmaVersion 2022 instead of 2020.

See one "problem" with varaible definitions in js class reported as error by eslint 2020:
https://t.me/ioBroker_development/28349 and
https://t.me/ioBroker_development/28355

If change is accepted, I could of course try to make a PR.
At first look change should be done here: https://github.com/ioBroker/create-adapter/blob/32d7657b11710f8a68519c2ee779ca9e4e9fc9b0/src/lib/core/questions.ts#L1124

**Comment by ticaki** [comment]
On this side https://node.green/#ES2023 u can check supported features of nodejs/ecma 18.18.2 is ecma **2023**.

To increase trust - is a link from here: https://nodejs.org/en/docs/es6/

**Comment by mcm1957** [comment]
Ok
When removing node 16 from creator 2023 could be used ....

**Comment by ticaki** [comment]
Didn't you write in Telegram that you were removing Nodejs 16 from the Creator?

**Comment by mcm1957** [comment]
Yes I did - comment should be a confirm to update to 2023 ... :-)

**Comment by AlCalzone** [comment]
I thought about this again. As this setting is merely used to get ESLint to parse new syntax, we might also set it to `esnext` and forget about it entirely.

**Comment by ticaki** [comment]
is this the same as `latest`?
