### ISSUE TITLE
TS2792: Cannot find module '@iobroker/adapter-core'.

### ISSUE THREAD

**Issue by DutchmanNL** [AlCalzone/create-adapter#1051]
when creating a new adapter module adapter-core cannot be found.

![Screenshot 2023-07-05 at 14 01 36](https://github.com/ioBroker/create-adapter/assets/7318445/261f9d94-da69-4d49-a9ed-9165a4304e78)

I used an tsconfig.json configuration of another adapter and that works well, diff between the one from adapter creator and the one I use successfully:

![Screenshot 2023-07-05 at 14 04 46](https://github.com/ioBroker/create-adapter/assets/7318445/b2ff7542-e8c7-40e9-9982-198a8bf0651a)

**Comment by AlCalzone** [comment]
Hmm strange. We normally test the compilation of generated adapters on CI.
Can you share your settings (`.create-adapter.json`)?

**Comment by AlCalzone** [comment]
AFAIK the line `"nodeResolution": "node"` __should__ be all that's necessary to fix this.

**Comment by DutchmanNL** [comment]
> AFAIK the line `"nodeResolution": "node"` **should** be all that's necessary to fix this.

Do no additional information needed? ☺️

**Comment by AlCalzone** [comment]
> Can you share your settings (`.create-adapter.json`)?

I'd still like to see this, so I can reproduce and fix it :)

**Comment by DutchmanNL** [comment]
> > Can you share your settings (`.create-adapter.json`)?
> 
> I'd still like to see this, so I can reproduce and fix it :)

sure here we go :)

```
{
	"cli": true,
	"target": "directory",
	"adapterName": "test-create",
	"title": "test-create",
	"expert": "yes",
	"features": ["adapter"],
	"adminFeatures": [],
	"type": "logic",
	"startMode": "daemon",
	"connectionType": "cloud",
	"dataSource": "push",
	"connectionIndicator": "yes",
	"language": "JavaScript",
	"nodeVersion": "16",
	"adminUi": "json",
	"tools": ["ESLint", "type checking", "Prettier"],
	"releaseScript": "yes",
	"devServer": "no",
	"indentation": "Tab",
	"quotes": "single",
	"es6class": "yes",
	"authorName": "DutchmanNL",
	"authorGithub": "DrozmotiX",
	"authorEmail": "rafal@drozmotix.eu",
	"gitRemoteProtocol": "HTTPS",
	"gitCommit": "no",
	"defaultBranch": "main",
	"license": "MIT License",
	"dependabot": "no",
	"creatorVersion": "2.4.0"
}
```

**Comment by AlCalzone** [comment]
Ok I can't reproduce:
![grafik](https://github.com/ioBroker/create-adapter/assets/17641229/46ee10da-b191-49a6-97ee-257f7fddbaa1)

![grafik](https://github.com/ioBroker/create-adapter/assets/17641229/7e2ea149-ef2e-478e-968a-66409314a239)

**Comment by DutchmanNL** [comment]
solution is to update typescript dev dependency to version >= 5.0.4
