### ISSUE TITLE
Creator still prompts for node 14 or node 16 / Please release new version

### ISSUE THREAD

**Issue by mcm1957** [AlCalzone/create-adapter#1052]
Node 14 has been removed already. PR #1041 and some others.
But this changes never got into a release.

So I still get the option to select 14 or 16 as minimum node release. Please consider releasing a new version.

![image](https://github.com/ioBroker/create-adapter/assets/28575778/42ad5e46-692f-4fc0-82bc-67f7b19a8e5d)

**Comment by AlCalzone** [comment]
Done: https://github.com/ioBroker/create-adapter/releases/tag/v2.5.0

**Comment by mcm1957** [comment]
Thansk very much for the fast response !
