### ISSUE TITLE
Fehlende Sprache UK

### ISSUE THREAD

**Issue by Standarduser** [AlCalzone/create-adapter#1072]
Der Adapter-Checker meldet
```
[W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
[W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
[W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
```

Im frisch generierten Adapter fehlt die Sprache UK. Diese sollte in der Vorlage hinzugefügt werden.

**Comment by AlCalzone** [comment]
Das ist seit einem halben Jahr schon drin => https://github.com/ioBroker/create-adapter/blob/master/CHANGELOG.md#240-2023-04-14

Bitte beim Ausführen des Creators das `@latest` nicht vergessen:
```
npx @iobroker/create-adapter@latest
```

**Comment by Standarduser** [comment]
Den betreffenden Adapter habe ich erst am 14. Oktober aus dem Latest erstellt, dennoch war UK nicht enthalten. Vielleicht ist da irgendwo noch ein Bug?

**Comment by AlCalzone** [comment]
Komisch dass es niemandem sonst aufgefallen ist. Ich schau es mir gerne nochmal an.

**Comment by ticaki** [comment]
Hab meinen Adapter ebenfalls letztens (09.2023) erstellt und das Problem nicht. Wobei ich nicht den neu erstellten geprüft habe. Zuerst habe ich mit jsonConfig.json rumgespielt und wohl auch mehrere Male npm run translate verwendet.

Neu erstellter Adapter:

```
[E200] Not found on npm. Please publish
[E801] No repository about text found. Please go to "https://github.com/ticaki/ioBroker.uktest", press the settings button beside the about title and add the description.
[E802] No topics found in the repository. Please go to "https://github.com/ticaki/ioBroker.uktest", press the settings button beside the about title and add some topics.
[E606] Current adapter version 0.0.1 not found in README.md
[W171] "common.title" is deprecated in io-package.json
[W170] "common.keywords" should not contain "iobroker, adapter, smart home" io-package.json
[W400] Cannot find "uktest" in latest repository
```

**Comment by AlCalzone** [comment]
Die Test-Baselines enthalten auch UK
