### ISSUE TITLE
Remove legacy support

### ISSUE THREAD

**Issue by mcm1957** [AlCalzone/create-adapter#1081]
As discussed (in short) at telegramm:

Please consider removing legacy support for new adapters completly. There's no real reson to create new adapters using "adapter.xxx" code. Especially with ESM mode in view it would be good to avaoid any new code based on global variables and not using classes.

@Apollon77 
@foxriver76 
@UncleSamSwiss 
@GermanBluefox 

Please fee free to comment / reject / approve

**Comment by AlCalzone** [comment]
Fine by me 👍🏻

**Comment by Apollon77** [comment]
ok for me too
