### ISSUE TITLE
ioPack should have `common.licenseInformation` instead of `common.license`

### ISSUE THREAD

**Issue by foxriver76** [AlCalzone/create-adapter#1087]
- and license field only in pack json
- see https://github.com/ioBroker/ioBroker.js-controller/pull/2591

**Comment by mcm1957** [comment]
Please release this change note before

- standard ioBroker github tests accept the new field
- repository checker can handle the new field 
- devPortal can handle the new field

othwise we would have to explain why a newly created adapter fails our own tests

**Comment by mcm1957** [comment]
If this testing is adapted, please check if this one https://github.com/ioBroker/testing/issues/577 can be done too. Its a little bit nasty to explicit remove the tests at code from files for wwwOnly adapters.
