### ISSUE TITLE
licenseInformation - template syntactically wrong 

### ISSUE THREAD

**Issue by mcm1957** [AlCalzone/create-adapter#1103]
The TEMPLATE is wrong:

https://github.com/ioBroker/ioBroker.example/blob/55c3807672e11b281be472120043e8f2aa656bb9/JavaScript/io-package.json#L56

Template:
```
        "license": "MIT",
        "licenseInformation": {
            "type": "free",
            "license": "MIT"
        },
```

common.license must be removed

**Comment by AlCalzone** [comment]
Are we sure there is nothing left that depends on the license field? Like a slightly older admin version? @Apollon77 @foxriver76

**Comment by mcm1957** [comment]
short: YES

long: 
- GH based tests require this. NO adapter will pass GH tests with both license and licenseInformation, so many adapters already contain licenseInformation only.
-  Repository builder generates required compatibility entries as far as I know for older admin

**Comment by AlCalzone** [comment]
Oh I see. Then we should fix this ASAP.
