### ISSUE TITLE
Support Release Script version 3

### ISSUE THREAD

**Issue by UncleSamSwiss** [AlCalzone/create-adapter#824]
Release Script version 3 has a new command line interface and a config file:
https://github.com/AlCalzone/release-script/blob/master/CHANGELOG.md#300-2021-09-15

This should be supported by the creator.

Also: don't forget to add the `iobroker` plugin.

**Comment by AlCalzone** [comment]
Note that there are a bunch of new features which are potentially useful:
* [replace version in more files](https://github.com/AlCalzone/release-script#replace-the-version-in-additional-files---versionfiles), e.g. in widgets, see https://github.com/AlCalzone/release-script/issues/51
* checking license files for outdated copyright years, see https://github.com/AlCalzone/release-script/issues/67 and https://github.com/AlCalzone/release-script#license-plugin-options
* [running scripts](https://github.com/AlCalzone/release-script#run-scripts-during-release-lifecycle---exec-or--x), e.g. to build TypeScript before release

**Comment by klein0r** [comment]
1. add ``package.json`` dev-dependencies:

```json
"devDependencies": {
  "@alcalzone/release-script": "^3.5.8",
  "@alcalzone/release-script-plugin-iobroker": "^3.5.8",
  "@alcalzone/release-script-plugin-license": "^3.5.8"
}
```

2. Add ``.releaseconfig.json`` file to project root

```json
{
    "plugins": ["iobroker", "license"]
}
```

3. Replace versions in widgets files

- ``widgets/template.html.ts``
- ``widgets/template.js.ts``

https://github.com/ioBroker/create-adapter/blob/fddfa801c07e0468ad17373fa9e1b82116ef4247/templates/widgets/template.html.ts#L15

https://github.com/ioBroker/create-adapter/blob/fddfa801c07e0468ad17373fa9e1b82116ef4247/templates/widgets/template.js.ts#L43

https://github.com/ioBroker/create-adapter/blob/fddfa801c07e0468ad17373fa9e1b82116ef4247/templates/widgets/template.js.ts#L14

When adding widgets ``.releaseconfig.json`` should look like this:

```json
{
  "plugins": ["iobroker", "license"],
  "versionFiles": [
      ["widgets/*.html", "(?<=version: \")(.*?)(?=\")"],
      ["widgets/*.js", "(?<=version: \")(.*?)(?=\",)"]
  ]
}
```

**Please check regex (untested)**

**Comment by mcm1957** [comment]
Please add "manual-review" plugin per default too as discussed at Meeting 2022-09-21.
@Apollon77 please confirm (if I am correct)

https://github.com/ioBroker/ioBroker.repochecker/issues/71 is related too
