### ISSUE TITLE
Use adapter-dev for translations

### ISSUE THREAD

**Issue by UncleSamSwiss** [AlCalzone/create-adapter#826]
The translation part of https://github.com/ioBroker/adapter-dev is written in a way that it can be used by create-adapter (including dummy translations for testing). We should thus switch to these libraries - and we will get all new translation features "for free" in the future.

https://github.com/ioBroker/adapter-dev/blob/641b3ff11470551ae2eedd14f72cf73e40a4749d/src/translate.ts#L15

**Comment by AlCalzone** [comment]
I think this is solved
