### ISSUE TITLE
Remove Unit-Testing from package.json and test/unit.js

### ISSUE THREAD

**Issue by klein0r** [AlCalzone/create-adapter#835]
It's a deprecated feature.

See https://github.com/ioBroker/testing/blob/6d5fb18d37317a438d0059284d4321f8a2292d2c/src/tests/unit/index.ts#L34-L44

**Comment by AlCalzone** [comment]
You can still use it to write your own unit tests, although one could  argue that those could go into a separate file.

**Comment by klein0r** [comment]
Ah okay, I thought it is recommended to write all tests in the `*.test.js` files

**Comment by AlCalzone** [comment]
Hmm, it doesn't actually add anything helpful over just using `*.test.js` files, so lets reopen this.
