### ISSUE TITLE
Set enabled to false by default in io-package.json

### ISSUE THREAD

**Issue by klein0r** [AlCalzone/create-adapter#836]
See

https://github.com/ioBroker/create-adapter/blob/8d32a125097dbbc021e3e3eeb0841b47087f0653/templates/io-package.json.ts#L69

as recommended in 

https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/objectsschema.md

```
common.enabled - mandatory [true/false] value should be false so new instances are disabled by default
```

**Comment by Apollon77** [comment]
In fact the "common best practoce" in the meantime is to enable them ... good discussion point

**Comment by UncleSamSwiss** [comment]
I would use the lawyer's answer: it depends.
If you need to configure your adapter before it can be used (and the configuration doesn't require the adapter to run), then I would probably disable it. In all other cases, I would enable it.
I think we should improve the documentation but leave it as-is in the creator.
