### ISSUE TITLE
Error (typescript): src/lib/tools.ts:80:13

### ISSUE THREAD

**Issue by Newan** [AlCalzone/create-adapter#847]
First compile:
```
src/lib/tools.ts:80:13 - error TS2571: Object is of type 'unknown'.
 } catch (e) {
80         if (e.response?.status === 429) {
           
```    
i change it to:
```

 } catch (e:any) {
        if (e.response?.status === 429) {
```

**Comment by AlCalzone** [comment]
I thought we had fixed this already. Will check tomorrow.

**Comment by AlCalzone** [comment]
Like in https://github.com/ioBroker/create-adapter/issues/846, I cannot reproduce. You seem to be using an outdated version of create-adapter. Make sure **not** to have it installed globally:
```
npm uninstall -g @iobroker/create-adapter
```
then run it as described here: https://github.com/ioBroker/create-adapter#usage

**Comment by Newan** [comment]
Error on my local machine, reinstall node fixed the error. thanks for the support
