### ISSUE TITLE
localLink problem

### ISSUE THREAD

**Issue by Steiger04** [AlCalzone/create-adapter#855]
localLink is always set for widgets and overwrites the VIS Edit link in the admin overview

[Link](https://github.com/ioBroker/create-adapter/blob/dc89fc2c79732c09386ec52b10e2df05b7c7995e/templates/io-package.json.ts#L73)

`${isWidget ? (`
			"restartAdapters": ["vis"],
			"localLinks": {"_default": "%web_protocol%://%ip%:%web_port%/vis/edit.html"},
		`) : ""}`

**Comment by Apollon77** [comment]
I think 
1.) It makes no sense to have several links to the same page
2.) It seems that Admin has an issue and the link from an adapter might override the vis link in suche a case ... strange

**Comment by AlCalzone** [comment]
I'm not using either of these features. If you can tell me what needs to be changed how, I can take care of it.

**Comment by Apollon77** [comment]
I would say: Remove the localLink
