### ISSUE TITLE
Repository url in package.json - git vs. git+https

### ISSUE THREAD

**Issue by klein0r** [AlCalzone/create-adapter#899]
Currently the protocol depends on the selection in the wizard:

https://github.com/ioBroker/create-adapter/blob/fddfa801c07e0468ad17373fa9e1b82116ef4247/templates/package.json.ts#L108-L110

But: The iobroker repo checker complains, if the value != ``git+https``.

Why isn't that value always ``git+https`` ? Github supports both in any case. See

https://docs.npmjs.com/cli/v7/configuring-npm/package-json#repository

**Comment by klein0r** [comment]
And the HTTPS Version should also end with ``.git``.

```javascript
const gitUrl = `git+https://github.com/${answers.authorGithub}/ioBroker.${answers.adapterName}.git`;
```

**Comment by AlCalzone** [comment]
Simple reason: I don't consider it necessary. A simple https URL is more approachable to humans.

> The iobroker repo checker complains

Then this check should be updated to accept valid settings IMO.

**Comment by klein0r** [comment]
> Then this check should be updated to accept valid settings IMO.

You're right, at the moment the checks are not complex enough and should accept ``git@github.com:....``
I will fix that.

https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories

> You can only push to two types of URL addresses:

> An HTTPS URL like https://github.com/user/repo.git
> An SSH URL, like git@github.com:user/repo.git

**Comment by AlCalzone** [comment]
Hmm, lets append the `.git` suffix to the https URL though.

**Comment by AlCalzone** [comment]
Or we could simplify and use one of the supported shorthands. I'd like that even more:

> For GitHub, GitHub gist, Bitbucket, or GitLab repositories you can use the same shortcut syntax you use for npm install:
> 
> ```jsonc
> {
>   "repository": "npm/npm",
>   "repository": "github:user/repo", // this one specifically
>   "repository": "gist:11081aaa281",
>   "repository": "bitbucket:user/repo",
>   "repository": "gitlab:user/repo"
> }
> ```

nonetheless, the checker needs to understand this.

**Comment by klein0r** [comment]
Ok, I've updated the checks in the repo checker to allow the following urls (based on github api):

Example: https://api.github.com/repos/klein0r/ioBroker.luftdaten

```json
  "git_url": "git://github.com/klein0r/ioBroker.luftdaten.git",
  "ssh_url": "git@github.com:klein0r/ioBroker.luftdaten.git",
  "clone_url": "https://github.com/klein0r/ioBroker.luftdaten.git",
```
