### ISSUE TITLE
eslint error when working on test files (TypeScript Adapter)

### ISSUE THREAD

**Issue by Garfonso** [AlCalzone/create-adapter#929]
Today I created a new adapter (create-adapter version 2.1.1). I created a typescript adapter. 

I then opened the file `tests/integration.js` and got an ESLint error from my IDE (WebStorm):
```
Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: test/integration.js.
The file must be included in at least one of the projects provided.
```

In `.eslintrc.js` the `parserObjects.project` option, that the error message mentions contains `'./tsconfig.json'` which, probably rightfully so, does only include *.ts files. There is a tsconfig.json in the test directory, too, that _should_ prevent this, from what I understand. So I played a bit with running ESLint from command line.
Running `eslint test/integration.js` in the root of the project throws the same error as in the IDE. Running ESLint in the test directory (i.e. `eslint integration.js`). So my question would be if VS Code (as the most used and proposed IDE) works in this case? Or if it does throw the same error? If so, then one could discuss this as an issue of the IDE (although command line is a bit problematic, too).

For WebStorm one mitigation was to just copy  the `.eslintrc.js` from root to the test folder, which makes sense, because ESLint / the IDE tries to find the "closest" `.eslintrc.js` file, also the test/eslintrc.js file will point to test/tsconfig.json in that case, which includes the test files. 
But TBH, I don't have much knowledge about that stuff. :smile:

**Comment by AlCalzone** [comment]
To fix, put this file into your test directory:
https://github.com/ioBroker/create-adapter/blob/b6bd25f8c8c2b40fed9a9f0b56094cf5fc414c15/test/baselines/adapter_TS_ES6Class_ESLint_Tabs_DoubleQuotes_MIT/test/.eslintrc.json

it is essentially the eslint config for a JS adapter. You might want to change some settings though (quotes or so).
