### ISSUE TITLE
Prettier (code formatting) just for TypeScript available, but not for JavaScript

### ISSUE THREAD

**Issue by Acgua** [AlCalzone/create-adapter#942]
"Prettier" as optional tool is offered for TypeScript only, but unfortunately not for JavaScript.

**TypeScript:**
![image](https://user-images.githubusercontent.com/95978245/185981191-9def71b5-16e3-443c-9bb1-d71c86e9769a.png)

**JavaScript:**
![image](https://user-images.githubusercontent.com/95978245/185981258-7cee56b7-6100-4363-8386-9d0f7f26da37.png)

Would be great to have this implemented for JavaScript as well. Thanks.

Used version: ioBroker adapter creator v2.1.1

**Comment by Acgua** [comment]
this is great, thanks AlCalzone! Ich kann gerne testen, wenn ich weiß, was ich in der Konsole eingeben kann, falls das überhaupt möglich ist.

**Comment by AlCalzone** [comment]
Schon selbst getested :)
Wenn die neue Version draußen ist, einfach beim JS-Adapter erstellen Prettier auswählen (vorher "ask me everything" angeben)
