### ISSUE TITLE
[SUGGESTION] Default for "receive regular dependency updates through Pull Requests" should be YES

### ISSUE THREAD

**Issue by mcm1957** [AlCalzone/create-adapter#970]
Suggestion / low prior

During creation of adapter the following question is output:

Do you want to receive regular dependency updates through Pull Requests?

According to the question, this option is recommended. 
So I would suggest to change the default for the answer from currently no to yes

**Comment by AlCalzone** [comment]
I like it. @Apollon77 what do you think?

**Comment by Apollon77** [comment]
do it
