### ISSUE TITLE
Outdated version of release script installed for new adapters 

### ISSUE THREAD

**Issue by mcm1957** [AlCalzone/create-adapter#974]
When creating a new adapter and selecting

 _Would you like to automate new releases with one simple command? ..._

AlCalzone's releasescritp is installed by default. 
BUT the version used is 2.2.2 while the current version of the AlCalcone/release-script is v3.5.9.

As an additional problem the release script v2.2.2 fails during translation with http error 504.

Furthermore the required plugins ('iobroker, "license", "manual-review"(*) ) should be installed and a .releaseconfig.json file should be created.

(*) Note: I recommend to add the manual-review plugin by default, thus enabling the check of translations. But feel free to discuss and omit it if you feel better this way.

Example og .releaseconfig.json
`{
  "plugins": ["iobroker", "license", "manual-review"]
}`

Attached a package.jsosn as  created by create-adapter at 2022-09-21:
[package.zip](https://github.com/ioBroker/create-adapter/files/9617870/package.zip)

**Comment by AlCalzone** [comment]
Related: #824
