### ISSUE TITLE
NPX is not using the latest version

### ISSUE THREAD

**Issue by TA2k** [AlCalzone/create-adapter#979]
Because of an issue of npx. The npx is not using the latest version 
https://github.com/npm/cli/issues/2329

It needs rm -rf ~/.npm/_npx  to delete the cache version
Maybe you add this in the readme or find a workaround

**Comment by mcm1957** [comment]
Already adapted at README.md by adding @latest to command.

https://github.com/ioBroker/create-adapter#usage

'delete' seems to be no longer required. So I think this can be closed
@AlCalzone
