### ISSUE TITLE
on docker hub ther is no node:12 anymore

### ISSUE THREAD

**Issue by oweitman** [AlCalzone/create-adapter#989]
https://github.com/ioBroker/create-adapter/blob/c3846294bc8aa31c450fbbe023471dab3b798ca7/templates/_devcontainer/parcel/_Dockerfile.ts#L10

error message from log during building of devcontainer
ERROR: Service 'parcel' failed to build: manifest for node:12 not found: manifest unknown: manifest unknown

**Comment by AlCalzone** [comment]
Oh I think we removed support for node 12 but forgot this spot.
