### ISSUE TITLE
devcontainer error in parcel container:  npm ERR! Missing script: "watch:parcel"

### ISSUE THREAD

**Issue by oweitman** [AlCalzone/create-adapter#990]
the created parcel container stops because where is no watch:parcel script in package.json

https://github.com/ioBroker/create-adapter/blob/8c208d4ba89f8cc753f2fa91c115a2695ee8e059/templates/package.json.ts#L167

error message in the logs of parcel container
```
Installing all dependencies...
up to date, audited 478 packages in 4s
100 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
npm notice 
npm notice New major version of npm available! 8.19.2 -> 9.1.2
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.1.2>
npm notice Run `npm install -g npm@9.1.2` to update!
npm notice 
npm ERR! Missing script: "watch:parcel"



```

the installed (test)-adapter configuration and other errors are described in thread
https://forum.iobroker.net/topic/36034/visualstudio-code-und-devcontainer/115

**Comment by mcm1957** [comment]
@AlCalzone 
Who can check / discuss this?

@oweitman 
Is this issue still reproduceable with latest version of adapter creator?

**Comment by AlCalzone** [comment]
> Is this issue still reproduceable

I think so, yes. There is exactly one occurence of `watch:parcel` and that's in the devcontainer script. Looks like that got forgotten when we switched the build process to `esbuild`: https://github.com/ioBroker/create-adapter/blob/master/docs/updates/20220215_esbuild.md

The devcontainer probably needs to be changed to use `esbuild`'s serve mode instead of parcel: https://esbuild.github.io/api/#serve
Happy to take a PR if someone finds the time to figure this out and test it.

@oweitman I strongly recommend to use https://github.com/ioBroker/dev-server/ instead of the devcontainer instead.

**Comment by oweitman** [comment]
it would not be that I would have tried the dev-server as well. but the situation is the same there. It is asked, but never answered to the end to reach a solution.
and this issue issnt opend by me, but i wrote the first time about this in forum
https://github.com/ioBroker/dev-server/issues/286

by the way, why create a PR. these are not implemented either
https://github.com/ioBroker/create-adapter/pull/992

**Comment by AlCalzone** [comment]
Please retry with the latest version of the dev server. If that doesn't work, please provide a concrete example/repo/commit someone can use to reproduce your problem.

Are you saying the linked PR fixes your issue?
If so, how can we verify it works? A problematic adapter for example?

**Comment by oweitman** [comment]
no the pr dosnt fix this issue.
as described it fix the not working websockets and addition removes a container that is useless, because there is no parcel anymore.
but i am repeating my self. please read the description of the pr

and you already wrote, that you missed yomething in changing from parcel to esbuild

**Comment by AlCalzone** [comment]
I'm repeating myself too: please provide a concrete example/repo/commit **someone can use to reproduce your problem**

Without that, this issue isn't likely to get fixed, as I (and likely the other devs too) am not going to spend my very limited time trying to read forum posts to figure out how to get to the same point you're stuck on.

Please make sure the issue description is complete and self-explanatory.
