### ISSUE TITLE
Transfer old adapter files

### ISSUE THREAD

**Issue by misanorot** [AlCalzone/create-adapter#993]
Hello,

I would like transfer my old adapter files into a new setup. The problem is, when I use the creator the creator tells me that the repo is used. How can I fixed this? My repos are alarm and Viessmann.

**Comment by AlCalzone** [comment]
Did you read the documentation? It's mentioned there 🙃

**Comment by misanorot** [comment]
skipAdapterExistenceCheck..... Hups
